### ISSUE TITLE
Better log messages

### ISSUE THREAD

**Issue by jackjansen** [jvdrhoof/WebRTCConnector#3]
Better log messages would be really beneficial. Right now, there is an incredible amount of information that cannot be understood unless you have the code right next to it.

Making a pass over all the messages and ensuring that each one prints information that is understandable would really speed development work up.

**Comment by jvdrhoof** [comment]
Better log messages are now provided, although some descriptions most likely still require technical background knowledge. Three console levels are considered:

- Log
- Warning
- Error

Error messages are (generally) printed out in a non-technical way, so that the user understands that services are impacted. Log messages contain information on different aspects:

- Incoming packets received over WebRTC from other peers (${\textsf{\color{green}green}}$)
- Outgoing packets sent over WebRTC to other peers (${\textsf{\color{Goldenrod}yellow}}$)
- Generic setup and logging (${\textsf{\color{orange}orange}}$)
- Technical errors (${\textsf{\color{red}red}}$)

Logging further makes use of a debug level:

- Default: generic setup information and potential error messages
- Verbose: additional information on the setup (limited number of messages)
- Debug: relevant information for each incoming/outgoing packet, buffer sizes, etc.
